### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by willirath** [willirath/nia-prediction-low-latitutdes#5]
997bfc6 has all the parts we need. Especially [this notebook](https://nbviewer.jupyter.org/github/willirath/nia-prediction-low-latitutdes/blob/997bfc6/poc_uv20.ipynb) shows how we can handle the 0.5 degree GFS fields with realatively small resources.

Next steps (not necessarily in this order):

- [x] Figure out publishing
  - [x] Evaluate the notebook(s) with [papermill](https://papermill.readthedocs.io/) as is, e.g., done in the [esm-vfc-workflows repo](https://github.com/ESM-VFC/esm-vfc-workflows/blob/803a77687f561623a040b285efcd6a9962861256/.github/workflows/main.yaml) and store as HTML
  - [x] Publish the HTML files with the [pages action](https://github.com/marketplace/actions/github-pages-action)
- [x] Optimize processing
  - [x] I'd like to pull the data to Zarr before doing the computation. As netCDF is single threaded, pulling the data from the Thredds server will scale with the number of processes in our Dask cluster. So we'll need a `n_workers=<many>, threads_per_worker=1` Dask cluster at this stage.
  - [x] Zarr can handle multithreaded IO so for better memory management, we'll need to switch (close and create new) to a cluster with `n_workers=1, threads_per_worker=<many>`.
  - [x] We could do with interpolating the wind data to 1 hour (at low to mid latitudes this may be overkill anyway?) just before integration and downsample the slab model outputs to 3 or even 6 hours immediately.

Note: Currently, [Github Actions have 6GB of memory and 14GB of SSD](https://docs.github.com/en/actions/reference/virtual-environments-for-github-hosted-runners#supported-runners-and-hardware-resources).

- [x] Split processing
  - [x] Have one notebook for obtaining the data (to Zarr)
  - [x] Have one notebook for the computation (to Zarr again)
  - [x] Have one notebook which only does the plotting (linking back to the other two for inspection)

- [x] Schedule runs: We want this to be up to date so we'll probably end up using the `schedule:` keyword in `.github/workflows/...` to make this run every 6 hours and time it to just after the new GFS forecast is published.
